### PR TITLE
Adding code coverage

### PR DESCRIPTION
**Pull request by markim**
Hello!

I liked how you had code coverage on the mocha test in the API project. It was easy to make a badge for my project to show the test percentage from the CI test stage. I wanted to see if I could get the code coverage of the vue app.

Here's full steps I did:
1.) Install base code coverage modules to developer dependencies
`npm install -D @cypress/code-coverage`
`npm install -D babel-plugin-istanbul`
`npm install -D istanbul-lib-coverage`
`npm install -D nyc`

edit: Don't actually need to run the spec reporter on this step. Kept the new command updates
2.) Update the npm scripts on package.json
- `"ci": "npm run ci:test && npm run coverage"`
- `"ci:test": "vue-cli-service test:e2e --env API_URL=https://api-demo.daniel-avellaneda.com,ENV=ci `~~--reporter spec~~` --headless --config video=false"`
- `"coverage": "nyc report --reporter=text-summary"`

3.) added istanbul plugin to babel.config.js
```javascript
module.exports = {
  presets: ['@vue/app'],
  plugins: ['istanbul']
}
```

4.) added tasks to the cypress plugins file
```javascript
  // Cypress code coverage support
  on('task', require('@cypress/code-coverage/task'))
  // Instrument code
  on('file:preprocessor', require('@cypress/code-coverage/use-babelrc'))
```

5.) added cypress coverage support on support file
`import '@cypress/code-coverage/support'`

6.) added nyc output and coverage files to git ignore
```
.nyc_output
/coverage/
```

The regular e2e test will run, but with the flag --reporter spec. By the end there will by a .nyc_output folder. Then, the `npm run coverage` command uses that .nyc_output folder to print out the coverage. It will print the coverage to the command line.

image

This also makes a /coverage/ folder that also makes an html report.

image

I don't know if this is useful, just wanted to share what I'm using in my own project.

Thanks for all your hard work Daniel!

### CODE REVIEW

**Comment by davellanedam** [comment]
This is really cool! Will check it this weekend as I’m relocating to Canada. Thank you so much for your help!

**Comment by markim** [comment]
@davellanedam Awesome! I had noticed a little inactivity, was wondering if you were OK! Hope the move goes well. Cheers!

**Comment by davellanedam** [comment]
Thanks for this, added it to master now!

**Comment by markim** [comment]
You're welcome! Thanks for adding it :)

Have a great 2020, friend

**Pull request closed without merging**
